[package]
name = "kyocode"
version = "0.1.0"
authors = ["sinkuu <sinkuu@sinkuu.xyz>"]
description = "Kyocode(経code) binary-to-text scheme implementation"
license = "MIT"

[dependencies]
ring = "0.12.1"
try_opt = "0.1.1"
arrayvec = "0.4.2"

[dev-dependencies]
quickcheck = "0.4.1"